server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/diruicloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    filters: wall,mergeStat
  dubbo:
    appname: consumer
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    port: 20800
  activemq:
    broker-url: tcp://127.0.0.1:61616
    close-timeout: 15s # 在考虑结束之前等待的时间
    in-memory: true # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    non-blocking-redelivery: false # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    password: 123456 # 密码
    send-timeout: 0 # 等待消息发送响应的时间。设置为0等待永远。
    user: admin
    packages:
      trust-all: true # 是否信任所有包
      trusted: # 要信任的特定包的逗号分隔列表（当不信任所有包时）
    pool:
      block-if-full: true # 当连接请求和池满时是否阻塞。设置false会抛“JMSException异常”。
      block-if-full-timeout: -1ms # 如果池仍然满，则在抛出异常前阻塞时间。
      create-connection-on-startup: true # 是否在启动时创建连接。可以在启动时用于加热池。
      enabled: false # 是否用Pooledconnectionfactory代替普通的ConnectionFactory。
      expiry-timeout: 0ms # 连接过期超时。
      idle-timeout: 30s # 连接空闲超时
      max-connections: 1 # 连接池最大连接数
      maximum-active-session-per-connection: 500 # 每个连接的有效会话的最大数目。
      reconnect-on-exception: true # 当有"JMSException"时尝试重新连接
      time-between-expiration-check: -1ms # 在空闲连接清除线程之间运行的时间。当为负数时，没有空闲连接驱逐线程运行。
      use-anonymous-producers: true # 是否只使用一个MessageProducer